### ISSUE TITLE
Extract/Process pictures from word docs?

### ISSUE THREAD

**Issue by frbapolkosnik** [deanmalmgren/textract#101]
I was trying to use textract against some word docs recently. There were a few pictures there, and no text.

How hard would it be to extract the pictures from the word docs and OCR them?

Thanks!

**Comment by deanmalmgren** [comment]
Sounds like you and @ankushshah89 are working with a lot of word docs. I can't speak to how difficult it would be to extract the pictures, but if we can get the image file it should be trivial to OCR them with tesseract. Are you dealing with `.doc` or `.docx` files?

In general, it seems like our `.doc`/`.docx` processing is particularly important and that we may need to be a bit more aggressive either (i) contributing to the upstream projects to make it easier for textract to do its thing or by (ii) writing our own stuff for addressing the weaknesses of these packages for our specific use case. I'm earnestly torn here and would appreciate opinions from the gallery...

**Comment by ankushshah89** [comment]
I think a  docx stores all the images in word/media folder. So, something as simple as:
```bash
unzip file.docx word/media/*.png
```
can extract all the *.png images. Although I am sure how/where to then integrate this piece in textract.

**Comment by ankushshah89** [comment]
Update: Added support for image extraction in [python-docx2txt](https://github.com/ankushshah89/python-docx2txt)

**Comment by deanmalmgren** [comment]
closed by #100
