### ISSUE TITLE
trouble with pdf documents

### ISSUE THREAD

**Issue by ViennaMike** [deanmalmgren/textract#103]
textract is very handy! Covers more file types and makes my code much simpler than when having to build my own code for each file type being handled. But maybe I'm missing something. When I try to do pdf files (ON WINDOWS), I get an error, e.g., 

> > > text = textract.process('C:\Users\mike\Documents\Work Stuff\PMI Practice Standard for Earned Value Management - Second Edition.pdf')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Users\mike\Anaconda\lib\site-packages\textract\parsers__init__.py", line 57, in process
> > >     return parser.process(filename, encoding, *_kwargs)
> > >   File "C:\Users\mike\Anaconda\lib\site-packages\textract\parsers\utils.py", line 44, in process
> > >     byte_string = self.extract(filename, *_kwargs)
> > >   File "C:\Users\mike\Anaconda\lib\site-packages\textract\parsers\pdf_parser.py", line 27, in extract
> > >     raise ex
> > > textract.exceptions.ShellError: The command `pdftotext  "C:\Users\mike\Documents\Work Stuff\PMI Practice Standard for Earned Value Management - Second Edition.pdf" -` failed with exit code 1
> > > ------------- stdout -------------
> > > ------------- stderr -------------
> > > 'pdftotext' is not recognized as an internal or external command,

operable program or batch file.

**Comment by deanmalmgren** [comment]
Oooo... I notice you're using textract on a Windows machine. There are a
lot of other third party programs on which textract depends. Check the
installation instructions for Ubuntu or OSX for ideas about how to get this
set up on Windows (sorry...but I have no idea about how to get `pdftotext`,
a Unix cmand line tool, installed on your system

http://textract.readthedocs.org/en/latest/installation.html

If you figure it out, please help us improve the documentation!

On Mon, Dec 21, 2015, 17:43 Mike McGurrin <notifications@github.com> wrote:

> textract is very handy! Covers more file types and makes my code much
> simpler than when having to build my own code for each file type being
> handled But maybe I'm missing something When I try to do pdf files, I get
> an error, eg,
>
> text = textractprocess('C:\Users\mike\Documents\Work Stuff\PMI Practice
> Standard for Earned Value Management - Second Editionpdf')
> Traceback (most recent call last):
> File "", line 1, in
> File
> "C:\Users\mike\Anaconda\lib\site-packages\textract\parsers__init__py", line
> 57, in process
> return parserprocess(filename, encoding, *
>
> *kwargs) File
> "C:\Users\mike\Anaconda\lib\site-packages\textract\parsers\utilspy", line
> 44, in process byte_string = selfextract(filename, **kwargs)
> File
> "C:\Users\mike\Anaconda\lib\site-packages\textract\parsers\pdf_parserpy",
> line 27, in extract
> raise ex
> textractexceptionsShellError: The command pdftotext
> "C:\Users\mike\Documents\Work Stuff\PMI Practice Standard for Earned Value
> Management - Second Editionpdf" - failed with exit code 1
> ------------- stdout -------------
> ------------- stderr -------------
> 'pdftotext' is not recognized as an internal or external command,
>
> operable program or batch file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deanmalmgren/textract/issues/103>.
>
-- 
*dean malmgren | +1.312.884.9214 *
*partner, data scientist | datascope*

**Comment by deanmalmgren** [comment]
I'm purging some old issues and I'm going to close this out. I would love to have a contribution to improve the Windows documentation. If you're up for it, some ideas for getting started are in #111.
