### ISSUE TITLE
Textract python "'module' object has no attribute 'process'"

### ISSUE THREAD

**Issue by Gerlo5** [deanmalmgren/textract#106]
Hi, I'm trying to use Textract in my python script (Python 2.7), but the following code:
`import textract
textract.process(filename)`
If i try to run the script, it raises the AttributeError 'module' object has no attribute 'process'.
If I execute the same two lines in python shell, it works.

**Comment by deanmalmgren** [comment]
It sounds like you may be importing the wrong thing from your script. There
is an executable called textract in the bin directory
<https://github.com/deanmalmgren/textract/blob/master/bin/textract> and
there is also a python package called textract
<https://github.com/deanmalmgren/textract/tree/master/textract>. I suspect
you may be importing the executable in your program when you actually want
to import the python package. To check, try printing sys.path in your
program to figure out which textract it is importing

Hope that helps,
Dean

On Sun, Feb 21, 2016, 07:21 Gerlo5 <notifications@github.com> wrote:

> Hi, I'm trying to use Textract in my python script (Python 2.7), but the
> following code:
> import textract
> textract.process(filename)
> If i try to run the script, it raises the AttributeError 'module' object
> has no attribute 'process'.
> If I execute the same two lines in python shell, it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deanmalmgren/textract/issues/106>.
>
-- 
*dean malmgren | +1.312.884.9214 *
*partner, data scientist | datascope*

**Comment by francesco1119** [comment]
Or, the error 

`AttributeError: 'module' object has no attribute 'process'`

might be given if your file is called `textract.py`

https://q-a-assistant.info/computer-internet-technology/converting-doc-to-pure-text-using-python/1359745
