### ISSUE TITLE
How to install textract on windows

### ISSUE THREAD

**Issue by chenwangliangguo** [deanmalmgren/textract#111]
after i use the commend "pip install textract on my windows machine", I found it can process the docx files. but cann't deal with doc and pdf files? any help can be appreciated

**Comment by deanmalmgren** [comment]
Thanks for using textract, @chenwangliangguo! 

There currently aren't any installation instructions for Windows, but [the basics of what you'll need are documented here](http://textract.readthedocs.io/en/latest/installation.html#don-t-see-your-operating-system-installation-instructions-here). If you figure out a way to install all of these packages on windows, please share your documentation and create a pull request!

I'm going to leave this issue open for the time being in case someone has gotten textract up and running on windows. 

The reason you're having trouble with doc files [is that doc files use `antiword` to extract the text](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/doc_parser.py#L9), which is a command line utility available on most unix systems. 

By default, [the pdf parser uses `pdftotext` to extract text](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/pdf_parser.py#L17), which is another command line utility that is installable on most unix systems. With pdf documents there are [other methods available though](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/pdf_parser.py#L29-L32). In particular, you should be able to use the `pdfminer` method to be able to process your pdfs.

**Comment by DeastinY** [comment]
Just stumbled upon this through Google - Did anything change ?
Is it possible to run this (partially) on Windows ? 
None of the different methods worked. Are there any alternatives for windows ?

**Comment by bamne123** [comment]
Thanks Deanmalmgren,  As per your comments I have tried to install commandline tool and it worked. 
Still struggling for DOC.
Steps for Pdf :
1. Download library from ftp://ftp.foolabs.com/pub/xpdf/xpdfbin-win-3.04.zip
2. Extract to any path, recommended to extract in Python or Anaconda Directory.
3. Add the path to Path environment variables.
4. Try to run from commandline, should be working.

**Comment by DeastinY** [comment]
Worked for me with the exact steps defined by @bamne123

**Comment by DeastinY** [comment]
While this worked for python scripts it fails when using in combination with pyinstaller. This might be my inexperience with pyinstaller tho. When I figure stuff out I'll add documentation !

**Comment by deanmalmgren** [comment]
Yeah... I don't know anything about pyinstaller :( Good luck!

**Comment by boralprophecy** [comment]
While installing on Windows 7 64 bit with Python 3.6 installed via Anaconda, doing

pip install textract

installs everything but shows the following error with EbookLib.

Though the higher version of EbookLib ( v0.16 ) is installed in my computer. But while I am trying to install v0.15 this error is happening. Any idea to skip installing EbookLib v0.15

![capture](https://user-images.githubusercontent.com/22155714/31072624-3dabeccc-a786-11e7-8834-7603f99cf66c.PNG)

**Comment by Michael-E-Rose** [comment]
We're having the same problem boralprophecy describes on Windows machines.  Additionally it doesn't work on a Mac for Python3, only Python2.  Only the Linux machine handles it without any error.

**Comment by scturner06** [comment]
@boralprophecy I managed to get it working by first installing EbookLib 0.16 and then

`pip install -U textract EbookLib==0.16`

Didn't manage to get the PDF reader working yet so working on that now.

**Comment by boralprophecy** [comment]
@scturner06  Got this error. Any idea how to overcome it please

![image](https://user-images.githubusercontent.com/22155714/31626192-6ce0cec2-b2c6-11e7-9c92-aae0f7a22862.png)

**Comment by scturner06** [comment]
@boralprophecy  You need to install a [swig compiler](http://www.swig.org/Doc1.3/Windows.html) and add it to your system PATH.

**Comment by akhil070** [comment]
How can i overcome this i don't want to install Visual studio code please help me...!
![error](https://user-images.githubusercontent.com/32274194/54202186-7d37dc80-44f5-11e9-816e-1c31880720f5.jpg)

**Comment by taqreez** [comment]
@akhil070  install swig from conda
conda install swig
if that does not work try: conda install -c conda-forge swig

**Comment by chingjunehao** [comment]
I had the same issue, it was because of the absent of Microsoft build tools. Check this out:
https://github.com/kpu/kenlm/issues/90

**Comment by jshihadeh** [comment]
@deanmalmgren I think i found a process for getting textract working on windows. https://github.com/deanmalmgren/textract/issues/194#issuecomment-506065817

thanks.

**Comment by nischal-sanil** [comment]
Another pocketsphinx error. Having a hard time clearing it. I have almost tried all the solutions present in this issue. 
![image](https://user-images.githubusercontent.com/42136912/61772140-2b8e4f80-ae0f-11e9-992f-5d017e5ace3f.png)
![image](https://user-images.githubusercontent.com/42136912/61772209-4fea2c00-ae0f-11e9-8b44-a17e5327a34d.png)

could anyone explain why this is happening?

**Comment by jpweytjens** [comment]
@nischal-sanil A new version of textract, `1.6.2`, is availble from this repo. This update makes pocketsphinx and it's dependency swig optional. While we're working on pushing this update to PyPi, can you can try installing textract from this repo with the following command?

`pip install git+https://github.com/deanmalmgren/textract.git`

**Comment by nischal-sanil** [comment]
Thanks, @jpweytjens It's working fine now.

**Comment by jpweytjens** [comment]
Closed by #292
