### ISSUE TITLE
npm3's flat node_modules structure causes 'not found' error when extracting text from Excel

### ISSUE THREAD

**Issue by PraneethVT** [deanmalmgren/textract#115]
There is a bug now because of npm3 when extracting text from Excel. 

Error: Could not extract usearch-1466710851433.xlsx, Command failed: /home/praneeth/Upward/uapi/node_modules/textract/node_modules/j/bin/j.njs ./test/tmp/xlsx/usearch-1466710851433.xlsx
/bin/sh: 1: /home/praneeth/Upward/uapi/node_modules/textract/node_modules/j/bin/j.njs: not found

Because of npm3's flat node_modules structure now, the "j" library cannot be found, it's now located in the same node_module folder as "textract" and everything else.

**Comment by deanmalmgren** [comment]
@PraneethVT I think you are looking for the [other textract project](https://github.com/dbashford/textract). Best of luck!
