### ISSUE TITLE
textract needs a co-maintainer

### ISSUE THREAD

**Issue by deanmalmgren** [deanmalmgren/textract#117]
I am totally floored by how much of a community effort `textract` has become over the last few years. We've added loads of new features, gone through a refactoring or two, and made several meaningful enhancements. Thanks to everyone who has helped make this happen!

Recently, my day job (which I love!) has kept me sufficiently busy that I've become irresponsibly delayed in my response to PRs that will benefit everyone. As a result, I am actively looking for someone to help me co-maintain this project. Realistically, it's probably only an hour or two of effort per week, if that. 

If you are interested, please let me know. I'd prefer that you express your interest by leaving a comment on this issue. If you'd rather be considered in private, it shouldn't be too hard to find my email address in the commit logs or to find me on Twitter.

I'm hoping to find a co-maintainer in the next week or two. Thanks for your consideration!

**Comment by deanmalmgren** [comment]
Paging @ShawnMilo @christomitov @pudo. Any interest in helping out with this?

**Comment by pudo** [comment]
Hey @deanmalmgren - first: congrats on the success of the project, it's really a brilliant piece of tooling. More recently, I've effectively ended up [re-building some components of this](https://github.com/pudo/aleph/tree/master/aleph/ingest) because I needed a more structured data to come out of extraction, i.e. the [management of metadata fields](https://github.com/pudo/aleph/blob/master/aleph/metadata/__init__.py#L36), and per-page outputs for document extracts. So I'm wondering if such a slightly more complex API is something you might consider as part of the future API of tesseract? If so, I'd love to chat further -- this might be mutually beneficial.

**Comment by ShawnMilo** [comment]
Thanks for the invitation. I was glad to be involved in it. These days I'm doing all Go and have pretty much left Python behind, and I also haven't been using textract at all, so I probably wouldn't be a good maintainer of the project. Sorry, but if I say yes I'll be overextending myself and probably do a crap job.

**Comment by deanmalmgren** [comment]
@pudo I'm certainly open to including metadata fields (see #47, for example). I've kept the textract API as simple as possible, but that seems like a really natural feature to add directly into textract. If you have experience doing so within your projects, that would expedite the process that much more! I'll reach out to you by email to see if we can't find a time to discuss these things further and I'll update this issue as we come closer to making a decision on this.

**Comment by deanmalmgren** [comment]
@ShawnMilo thanks for the reply; I completely understand! Hope you're projects are going well

**Comment by akoumjian** [comment]
I might be interested. I'll be putting in a couple PRs in the coming days/weeks, perhaps you can use them to decide whether or not I'd be a good fit. Right now I'm using textract pretty heavily for a project and I think it's the bee's knees.

**Comment by deanmalmgren** [comment]
Sounds good, @akoumjian. I'm glad you're enjoying textract and I appreciate your willingness to contribute. I like your suggestion to revisit in the coming days/weeks and I look forward to your PRs :)

**Comment by deanmalmgren** [comment]
Hi all. I have some exciting news: @jpweytjens and @DanielSwain have agreed to come on to the project as collaborators and, over the coming months, will even become the primary maintainers of `textract`. This is a really exciting turning point in the history of this project and I’d like to take a moment to acknowledge the overwhelming support and interest in `textract` from the broader community. I never thought a simple little tool like `textract` would turn into such a commonly used tool and I’m thrilled by all of your interest and usage.

I have been grossly negligent in responding to issues and pull requests over the past few years, but if it’s any consolation, I have done that intentionally. I have not had the time to support this project for the couple of hours per week that it requires, and I couldn’t, in good conscience, respond to some issues without responding to them all. Please accept my apologies for this approach, but it was the only way I could reasonably manage my sanity and coax someone else to carry the torch.

@jpweytjens and @DanielSwain will be starting by digging into some of the more gnarly dependency issues across systems when installing `textract` but, over the coming months, they will take over responsibility across the broader codebase. The plan is for @jpweytjens to ultimately take over primary responsibilities with @DanielSwain supporting as time allows. While they are getting used to the codebase, I will continue to serve as a mentor and have responsibilities for pushing new versions to PyPI. Please be patient and give them the benefit of the doubt as they are getting used to this new role.

**Comment by jpweytjens** [comment]
I'm closing this issue as @DanielSwain and I have resolved, what we hope are, the most pressing issues. We're still digging through some of the older issues and pull requests. Please feel free to close old and resolved issued, open new issues and submit pull requests. We'll happily take a look at these.
