### ISSUE TITLE
Different Results CLI vs. Library

### ISSUE THREAD

**Issue by thecapacity** [deanmalmgren/textract#118]
I'm using textract for a project parsing google docs when have been exported to PDF.

When I use the CLI the text is great, but when I call it in my python code there are no spaces b/t most (almost all) of the words.

Here's the function call `>>> t = textract.process( join(bot.my_data_dir, f), encoding="ascii")`

Is there something in the CLI that causes it to generate better output?

Thanks for an awesome tool and library!

**Comment by thecapacity** [comment]
It's interesting, the file generated from the CLI looks good, e.g. text such as; 

"of Information Technology / IT Operations. The IT Operations. The IT Operations organization is"

But when it's parsed again with textract the "spaces" are removed, i.e.

"ofInformationTechnology/ITOperations.TheITOperations.TheITOperationsorganizationis"

```
        file_list = [f for f in listdir(my_dir) if isfile(join(my_dir, f))]

        for f in file_list: # Will overwrite text for any existing files
            print "\tProcessing file:", f
            self.everything['input'][f] = textract.process( join(my_dir, f), encoding="ascii" )
            print self.everything['input'][f]
```

-------
When I look at the file in hexdump -c it looks like the "spaces" are a combination of `<C2><A0>`  (0xC2 followed by 0xA2)

Which seem to be;
* "nonbreaking space" - http://www.fileformat.info/info/unicode/char/a0/index.htm
* "left to right" - http://www.fileformat.info/info/unicode/char/c2/index.htm

I'm asking textract to extract ascii so it makes sense it would drop them, but it feels like non-breaking space should be converted to " "?

**Comment by deanmalmgren** [comment]
I think you're right that the `ascii` encoding is causing problems. The `BaseParser.encode` method ignores characters the specified codec can't handle. You might want to try a codec like utf8 that has a larger number of character code points.

Equivalently, you can specify the ascii encoding on the command line to see the same result.

**Comment by thecapacity** [comment]
thanks @deanmalmgren here's what I ended up doing:
```
            txt = textract.process( join(my_dir, f), encoding="utf-8" )
            txt = txt.replace("\xa0", " ")
            txt = txt.decode('ascii', errors="ignore")
            txt = txt.encode("ascii") #, errors="ignore") # redundant given the decode above(...)
            self.everything['input'][f] = txt
```
Versus having `textract` extract to ascii directly

**Comment by deanmalmgren** [comment]
Nice; glad you were able to find a good solution to this
