### ISSUE TITLE
Error attempting to textract a doc file with a backquote (backtick) (grave accent) in the file name

### ISSUE THREAD

**Issue by qsebas** [deanmalmgren/textract#124]
if the process is run with a word file having a backquote in the name, the process return the following error:

failed with exit code 2\n------------- stdout -------------\n------------- stderr -------------\n/bin/sh: 1: Syntax error: EOF in backquote substitution\n\n

the problem is in the doc_parser.py file
        stdout, stderr = self.run('antiword "%(filename)s"' % locals())

this line construct a shell command line  without escaping the backquote

**Comment by qsebas** [comment]
this bug is solved in the PR #114 (solving similar problems for other file extensions) 
it would be great if this PR is included in the next version

**Comment by deanmalmgren** [comment]
Thanks for the heads up @qsebas. I just merged #124 and I'll close this issue out. If you still run into issues, please feel free to reopen.
