### ISSUE TITLE
couldn't open a tmp file with 1.5 that I can with 1.4

### ISSUE THREAD

**Issue by SwedishBotMafia** [deanmalmgren/textract#131]
No Idea where the regression is but someone should know. I reverted my version to make it work... But really?

**Comment by SwedishBotMafia** [comment]
used NamedTemporaryFile, loaded a pdf that had UTF-8 encoding. passed the temp file name to textract.process and it claimed the file didn't exist each time.

**Comment by SwedishBotMafia** [comment]
1.4 has no such issue.

**Comment by deanmalmgren** [comment]
Hey @SwedishBotMafia, I'm sorry to hear that you're having trouble. Can you provide us with a bit more information so we can help you resolve it?

* What operating system are you using?
* Can you share a code snippet (in python or on the command line) that breaks?
* Can you share the traceback information?

This is pretty surprising considering no one else has reported the issue and all tests are passing on 1.5 (which certainly tests that functionality). I suspect something else is going on here...

**Comment by SwedishBotMafia** [comment]
Sure give me a day or two, will post some pdb stuff this weekend.

**Comment by SwedishBotMafia** [comment]
I suspect that we didn't have all of the apt-get dependencies and it caused some weirdness. I reinstalled it on a few different boxes and set up some test cases and it worked.

**Comment by deanmalmgren** [comment]
ok; thanks for following up @SwedishBotMafia!
