### ISSUE TITLE
Misleading error message when pdftotext dependency not installed

### ISSUE THREAD

**Issue by richardpenman** [deanmalmgren/textract#132]
On OSX I tried parsing a PDF and got a file not found error:

    $ textract.process(pdf_filename)
    ....
    OSError: [Errno 2] No such file or directory

Installing the pdftotext backend fixed this.

**Comment by deanmalmgren** [comment]
Thanks for sharing. This is related to #130. It seems that we generally need a way to remind people to install all dependencies...

**Comment by deanmalmgren** [comment]
closed by #139
