### ISSUE TITLE
Process PDF document with encoding issue

### ISSUE THREAD

**Issue by njoannin** [deanmalmgren/textract#133]
I am having trouble reading a PDF file with encoding utf-8...

The main issue I'm having is that although I specify the encoding, it seems like it is using a different encoding (iso8859_8).

Is this the expected behaviour?

```
>>> t = textract.process(f, encoding='utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\njoannin\i2e_py35_venv\lib\site-packages\textract-1.5.0-py3.5.egg\textract\parsers\__init__.py", line 58, in process
    return parser.process(filename, encoding, **kwargs)
  File "C:\Users\njoannin\i2e_py35_venv\lib\site-packages\textract-1.5.0-py3.5.egg\textract\parsers\utils.py", line 46, in process
    unicode_string = self.decode(byte_string)
  File "C:\Users\njoannin\i2e_py35_venv\lib\site-packages\textract-1.5.0-py3.5.egg\textract\parsers\utils.py", line 65, in decode
    return text.decode(result['encoding'])
  File "C:\Users\njoannin\i2e_py35_venv\lib\encodings\iso8859_8.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0xc2 in position 5004: character maps to <undefined>
```

**Comment by deanmalmgren** [comment]
Thanks for reporting this issue and I'm sorry you've run into trouble. Encodings are tricky.

textract guesses the encoding using [charset](https://github.com/chardet/chardet) and then encodes the output as specified. In this case, it seems that textract/chardet are not doing a good job of guessing the incoming encoding. 

Can you share the output of chardet on your file?

For reference, here is the place where textract does the "unicode sandwich"

**Comment by deanmalmgren** [comment]
Damn it. Sorry about that. Accidentally hit close button while on my phone.

Anyway, textract handles encoding in [textract.parsers.utils.BaseParser.process](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/utils.py). Hopefully that points you in the right direction.

Perhaps we should also consider having an `input_encoding` so we aren't so reliant on chardet getting things right. Did you know beforehand that the encoding was iso8859_8?

**Comment by njoannin** [comment]
Hmm, I am a little confused. I assumed that if I added in the argument `encoding='utf-8'`, well that it would take that instead of trying to guess it... 

Second, the output that I originally posted is the error message I get when trying the utf-8 encoding. It looks like (according to the error message) that it tries to use iso8859_8. I have no idea why.

To answer your question about chardet output (from the command line):

```
chardetect 23706679.pdf
23706679.pdf: no result
```

From Python:

```
>>> chardet.detect(open('23706679.pdf').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\whatever\i2e_py35_venv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6188: character maps to <undefined>
```

Reading your last comment, yes I think it could be useful to have the option of stating the input encoding.

**Comment by deanmalmgren** [comment]
Yeah, I can see how this "output encoding" thing is confusing. It certainly sounds like something that is worthy of fixing. Looking back at #39 (particularly [this comment](https://github.com/deanmalmgren/textract/pull/39#issuecomment-52344465)) reminded me of some things that made encoding particularly tricky.

Just to make sure that an `input_encoding` would help (and that this isn't an odd problem with this particular file), does the following work?

```
with open('23706679.pdf') as stream:
    byte_string = stream.read()
    unicode_string = byte_string.decode('iso8859_8')
    result = textract.process(unicode_string)
```

Adding input encodings—and while we're at it, giving users flexibility to handle how the unicode errors are handled—definitely sound like a good idea. I just want to make sure this addresses real problems people are having with textract.

Thanks again with your help on this!

**Comment by njoannin** [comment]
Here's the output:

```
>>> with open('23706679.pdf') as stream:
...    byte_str = stream.read()
...    unicode_str = byte_str.decode('iso8859_8')
...    result = textract.process(unicode_str)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\njoannin\i2e_py35_venv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6188: character maps to <undefined>
```

Hope this helps!

**Comment by deanmalmgren** [comment]
Huh. It still seems to be breaking on the `byte_str.decode` statement. Are you sure that file is encoded as iso8859_8?

I don't mean to pry, but if there's a way to share this file (or something similar), I can take a closer look to see what's going on... You can DM me a link to the file on twitter or my email is first dot last at datascopeanalytics dot com

**Comment by njoannin** [comment]
I do not believe the file is encoded with that encoding. As I said in the initial comment, I was trying to force it to use utf-8, but it looked like charmap was trying to use iso8859_8.

Through your comments, I gathered that it is not possible to force the use of a specific encoding, and that charmap will always try to guess, and that we have no control over it.

I like your suggestion to make it possible to add the input encoding, but that is up to you to decide whether it is a real problem for most people or not. 

Regarding my file, unfortunately, I cannot share it, but I worked around the issue for this particular file so I don't need a fix anytime soon...

Also, thanks for your prompt replies and help!

**Comment by deanmalmgren** [comment]
It just occurred to me. `textract.process` takes a `filename`, not the _content_. What was `f` in your original post?

**Comment by njoannin** [comment]
`f` is a filename.

**Comment by deanmalmgren** [comment]
@njoannin I was just digging into this a bit and I suspect this might be due to a version problem with `chardet`. I just pinned `chardet` to version 2.1.1 in our requirements file and pushed it to master (not released on pypi yet). This fixed #107 and I suspect it will address your issue too. Can you please confirm?

**Comment by njoannin** [comment]
@deanmalmgren Thanks for the update!

I am no longer working with this. I will close this issue for now. If I find that I still encounter the problem, I'll reopen it.

**Comment by tvrbanec** [comment]
@deanmalmgren
SOME pdf files just get stucked with decoding. Like this:

  File "/usr/local/lib/python2.7/dist-packages/textract/parsers/__init__.py", line 77, in process
    return parser.process(filename, encoding, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/textract/parsers/utils.py", line 47, in process
    unicode_string = self.decode(byte_string)
  File "/usr/local/lib/python2.7/dist-packages/textract/parsers/utils.py", line 65, in decode
    return text.decode(result['encoding'])
  File "/usr/lib/python2.7/encodings/cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 583: character maps to <undefined>

I am using chardet==2.3.0. But if I upgrade gensim, I get chardet==3.0.4. Problem remains. If we can't fix this, is it possible too include some exeption which will ignore problematic pdf file(s), with some info?

**Comment by tvrbanec** [comment]
OK.
I have done it myself:

def extract_txt(file):
    try:
        txt = textract.process(file)
    except UnicodeDecodeError:
        print 'File', file, 'cannot be extracted! - skipped'
        txt = ''
    return txt

**Comment by Ziinc** [comment]
```
/usr/local/lib/python3.7/site-packages/textract/parsers/__init__.py in process(filename, encoding, extension, **kwargs)
     75 
     76     parser = filetype_module.Parser()
---> 77     return parser.process(filename, encoding, **kwargs)
     78 
     79 

/usr/local/lib/python3.7/site-packages/textract/parsers/utils.py in process(self, filename, encoding, **kwargs)
     45         # http://nedbatchelder.com/text/unipain/unipain.html#35
     46         byte_string = self.extract(filename, **kwargs)
---> 47         unicode_string = self.decode(byte_string)
     48         return self.encode(unicode_string, encoding)
     49 

/usr/local/lib/python3.7/site-packages/textract/parsers/utils.py in decode(self, text)
     63         # use chardet to automatically detect the encoding text
     64         result = chardet.detect(text)
---> 65         return text.decode(result['encoding'])
     66 
     67 

/usr/local/lib/python3.7/encodings/cp1254.py in decode(self, input, errors)
     13 
     14     def decode(self,input,errors='strict'):
---> 15         return codecs.charmap_decode(input,errors,decoding_table)
     16 
     17 class IncrementalEncoder(codecs.IncrementalEncoder):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 875: character maps to <undefined>
```

I think passing in a `errors='ignore'` kwarg would prevent the breaking of code execution

**Comment by arevuzDisaitek** [comment]
Hello, this issue is still here. Is there something a can do to solve the problem now?

**Comment by pablogps** [comment]
I am also having this problem: encoding is wrong and I can't change it.
