### ISSUE TITLE
docs still broken for v1.6.0

### ISSUE THREAD

**Issue by deanmalmgren** [deanmalmgren/textract#152]
arg. #150 did not fix the problem

now [readthedocs is complaining](https://readthedocs.org/projects/textract/builds/5264293/) about not being able to find the recent version of SpeechRecognition:

> ...
> Installed /home/docs/checkouts/readthedocs.org/user_builds/textract/envs/latest/lib/python2.7/site-packages/textract-1.6.0-py2.7.egg
> Processing dependencies for textract==1.6.0
> Searching for pocketsphinx==0.1.3
> Reading https://github.com/mattgwwalker/msg-extractor/zipball/master
> Reading https://pypi.python.org/simple/pocketsphinx/
> Downloading https://pypi.python.org/packages/e1/e8/448fb4ab687ecad1be8708d152eb7ed69455be7740fc5899255be2228b52/pocketsphinx-0.1.3-py2.7-linux-x86_64.egg#md5=1b4ce66e44f53d23c981e789f84edf29
> Best match: pocketsphinx 0.1.3
> Processing pocketsphinx-0.1.3-py2.7-linux-x86_64.egg
> creating /home/docs/checkouts/readthedocs.org/user_builds/textract/envs/latest/lib/python2.7/site-packages/pocketsphinx-0.1.3-py2.7-linux-x86_64.egg
> Extracting pocketsphinx-0.1.3-py2.7-linux-x86_64.egg to /home/docs/checkouts/readthedocs.org/user_builds/textract/envs/latest/lib/python2.7/site-packages
> Adding pocketsphinx 0.1.3 to easy-install.pth file
> 
> Installed /home/docs/checkouts/readthedocs.org/user_builds/textract/envs/latest/lib/python2.7/site-packages/pocketsphinx-0.1.3-py2.7-linux-x86_64.egg
> Searching for SpeechRecognition==3.6.3
> Reading https://pypi.python.org/simple/SpeechRecognition/
> No local packages or working download links found for SpeechRecognition==3.6.3
> error: Could not find suitable distribution for Requirement.parse('SpeechRecognition==3.6.3')

**Comment by barrust** [comment]
Do you think this was due to an issue with that library at the time of building? I tried installing SpeechRecognition=3.6.3 locally and it worked fine. It is odd that it would not work on read the docs.

**Comment by deanmalmgren** [comment]
Thanks for the prompt, @barrust! It's been a busy few weeks and I hadn't looked into this in a while. 

For some reason, I had it in my head that textract, and all of its dependencies, need to be installed on the system for the docs to be built. I seem to recall this having to do with using `sphinx-argparse` to auto-document the command line interface.

Looking at it a bit more closely this morning, I'm realizing that `sphinx-argparse` probably does not necessarily need all of the dependencies installed in order to build the documentation. Which is to say that we may be able to address the problem by changing the RTD build to only installing certain packages and NOT installing textract. I think we can do by [configuring RTD](http://docs.readthedocs.io/en/latest/builds.html) to not install the package. On my phone at the moment; I will give this a try soon-ish!

**Comment by deanmalmgren** [comment]
closed by #158
