### ISSUE TITLE
.ppt format not supported 

### ISSUE THREAD

**Issue by hack-er** [deanmalmgren/textract#153]
The filename extension .ppt is not yet supported by
textract. Please suggest this filename extension here:

    https://github.com/deanmalmgren/textract/issues

asked, and answered :)

**Comment by deanmalmgren** [comment]
Thanks for mentiinjng it. PRs welcome! I messed around with a few things in #63 but wasn't terribly satisfied in the results.

**Comment by jpweytjens** [comment]
`ppt` files will be supported in the upcoming version.
