### ISSUE TITLE
The filename extension .pdf is not yet supported by textract

### ISSUE THREAD

**Issue by MJK88** [deanmalmgren/textract#156]
I compiled a python script to an executable in which I want to read a pdf with textract. In my Python editor this works without problems.  But when a execute the .exe file I get the warning: The filename extension .pdf is not yet supported by textract. Obviously, not true. Anybody knows how I can fix this?

**Comment by DeastinY** [comment]
I can't help, but I'm currently in the exact same boat:
```File "site-packages\textract\parsers\__init__.py", line 53, in process
textract.exceptions.ExtensionNotSupported: The filename extension .pdf is not yet supported by
textract. Please suggest this filename extension here:

    https://github.com/deanmalmgren/textract/issues

Failed to execute script gui
QWaitCondition: Destroyed while threads are still waiting
```

**Comment by deanmalmgren** [comment]
I'm sorry to hear you're having trouble extracting text from PDFs. Can you tell me a bit more about your setup (OS, textract version, etc)? It would also be helpful to see the actual command you are trying to run so I can try to reproduce.

Since you mentioned ".exe", I'm guessing you're on a Windows system. #155 looks like it is grappling with similar issues. My hunch is that your `PATH` (in unix, this variable controls where it looks for executables but I don't know the Windows equivalent) is different from within the python interpreter vs when you're using `textract` on the command line.

I have never actually installed textract on a Windows system—please feel free to add documentation about how you got it installed (see #111)!

**Comment by DeastinY** [comment]
Hey @deanmalmgren, thanks for the super fast reply !
I'm just confused by the `The filename extension .pdf is not yet supported by
textract` - is this the output if textract is not set up properly ?
I added the required stuff (pdftotext) to my PATH - nothing changed.
If I get everything set up properly I will surely add some documentation, this is a great project !

**Comment by deanmalmgren** [comment]
That is the error message that is reported when a [`ExtensionNotSupported`](https://github.com/deanmalmgren/textract/blob/master/textract/exceptions.py#L14-L32) error is raised. I believe that error is only thrown [here](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/__init__.py#L67-L72), when it tries to import the filename extension.

Can you share more about your system configuration and the verbatim code (or at least as close to it as possible) so I can help you diagnose?

**Comment by DeastinY** [comment]
What I tried so far:
- Install [Tesseract for Windows](https://github.com/UB-Mannheim/tesseract) and add it to PATH
- Install [pdftotext](ftp://ftp.foolabs.com/pub/xpdf/xpdfbin-win-3.04.zip) and add it to PATH
- Try moving the executables from those to the resulting file run dir

The textract version I'm using is 1.5.0, Python 3.6.1 and dev branch of pyinstaller.
For the source code I'm working on it's [here](https://github.com/DeastinY/srpdfcrawler) - but currently still in a pretty bad shape. Basically all I'm doing is `textract.process(str(file_pdf)).decode('utf-8')`

**Comment by deanmalmgren** [comment]
hmmmm... this is really odd. I take it back; this has nothing to do with the PATH (or at least it doesn't appear that this is the problem). The error is thrown before its even getting to the PDF parser.

Can you try manipulating the [textract/parsers/__init__.py](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/__init__.py#L54) file in your local version? 

It appears that [this line](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/__init__.py#L68-L70) isn't working properly with your setup for some reason. It should be doing something like `importlib.import_module('.pdf_parser', 'textract.parsers')` but that appears to be throwing an `ImportError`. 🤞

**Comment by DeastinY** [comment]
Thanks a bunch for clarifying - was looking through the code but had very little idea of what it was actually doing 😄 
I am not exactly sure how to manipulate those but I'll try out some things and report back

**Comment by DeastinY** [comment]
Okay, so what I did to **use Textract to extract PDF using pdftotext on Windows with Pyinstaller**:

- Set up `pdftotext.exe` somwhere so that it's executable for Python.
  - Option A: Add it to the pyinstaller `.spec` file like this `datas=[('pdftotext.exe', '.')],`
  - Option B: Add it to the Windows PATH environment
- Configure PyInstaller
  - Add the parsers you want to use to the `.spec` file in the `hiddenimports` section e.g. `hiddenimports=["textract.parsers.pdf_parser"],`
  - *( Not sure if required )* Add `pathex=['PATH\\TO\\Python\\Python36\\Lib\\site-packages\\textract\\parsers'],`

*I only have very basic experience using pyinstaller, this might be a wrong/bad way to do it, but it works.*

**Comment by deanmalmgren** [comment]
@DeastinY I don't know what happened when I uploaded textract to pypi, but I just realized that the `v1.6.0` release never made it onto pypi for some reason. I just pushed v1.6.0 to pypi now. This is probably why your version of textract looked so different. My apologies for the problem there. 

There are [several fixes in 1.6.0](https://github.com/deanmalmgren/textract/blob/master/docs/changelog.rst#160), including #136 which improved the parser imports. I'm cautiously optimistic that this will help with some things. 

I'm terribly sorry for the inconvenience. I thought I had released 1.6.0 but apparently it didn't fully upload to pypi or something :(

**Comment by DeastinY** [comment]
> I'm terribly sorry for the inconvenience. 
I'm super happy I can rely on such a great Open Source tool for my project. Your instant support and help with debugging was super helpful and I'm very happy I could at least help identify a failed push for 1.6.0 :D
Once again tthank you so much for the effort you put into this great project and the provided suppert ! 💓

**Comment by MJK88** [comment]
To follow up after your discussion on this problem. I used a similar setup. I use Python 2.7, and the compiler Py2exe, which works similar as pyinstaller. I installed textract on Windows with the command line: 'pip install textract', back then it was version 1.5.  After your messages I tried to include 'textract.parsers.pdf_parser' similar as in the spec-file of pyinstaller but in the options file of Py2exe `'includes': ['textract.parsers.pdf_parser']`. This didn't fix it. Then I updated textract to version 1.6.1, by using the command line: 'pip install textract --upgrade'. This fixed it for me. The compiled executable doesn't give the error anymore. I didn't test the dependency of the module inclusion yet. Thanks for the quick support and discussion!

**Comment by deanmalmgren** [comment]
Great; I'm glad we have this resolved. Thanks for the discussion everyone.

**Comment by lrq3000** [comment]
Confirmed, to make textract work with pyinstaller, one has to both:
* update textract to v1.6.1 (maybe v1.6.0 works too but did not try).
* add the parsers to the hiddenimport in spec file for pyinstaller: `hiddenimports=['textract.parsers.pdf_parser']`

Nothing else is needed! Thanks a lot for the great job!

**Comment by lrq3000** [comment]
Update: adding 'textract.parsers.pdf_parser' to hiddenimports will only allow for support of pdf files, but not any other type normally supported by Textract!

You can guess why: we need to add ALL parsers as hidden imports! Here is how I did it:

```python
import textract
textract_all_parsers = list(os.walk(os.path.join(os.path.dirname(textract.__file__), 'parsers')))[0][2]
textract_all_parsers_imports = ['textract.parsers.' + os.path.splitext(parser)[0] for parser in textract_all_parsers]

a = Analysis([...,
hiddenimports=textract_all_parsers_imports,
...
])
```

**Comment by harshu12345** [comment]
What the fuck that "`hiddenimports=["textract.parsers.pdf_parser"],` for the hidden import."

**Comment by harshu12345** [comment]
What the fuck that "`hiddenimports=["textract.parsers.pdf_parser"],` for the hidden import."
