### ISSUE TITLE
textract unable to  process remote files 

### ISSUE THREAD

**Issue by hubert10** [deanmalmgren/textract#157]
I have been struggling  to extract pdf file content stored in Amazon S3 through url but my function 
  
  import textract

        def parse_to_string(filename):

            return textract.process(filename)
     
doesn't  work. How can I make this work?
Thanks!!!!

**Comment by deanmalmgren** [comment]
Hey @hubert10! Thanks for raising the issue. textract is designed to work on files that are downloaded locally at the moment. A quick workaround would be to download the file locally from S3 and then run textract on the local filename:

```python
import textract
import requests

def download(url, filename):
    r = requests.get(url, stream=True)
    with open(filename, 'wb') as fd:
        for chunk in r.iter_content(chunk_size):
            fd.write(chunk)


def parse_to_string(url):
    filename = "????"
    download(url, filename)
    return textract.process(filename)
```

**Comment by hubert10** [comment]
Hey @deanmalmgren, thanks for the  fast reply!
I was trying to make it work as now I undestand that I have first to download my files locally, but this function: 

``` 
 def  download(url, filename):
     r = requests.get(url, stream=True)
      with open(filename, 'wb') as fd:
         for chunk in r.iter_content(chunk_size):
             fd.write(chunk)
```
should return smething right?

**Comment by hubert10** [comment]
Hello I came up doing it. Thank you so much!

```       url = "http://exapmple.com/medias/" + data['file']
        r = requests.get(url)
        with open(path + data['file'].split("/")[2], "wb") as f:
                     f.write(r.content)
```

**Comment by deanmalmgren** [comment]
oh good! i'm glad you figured something out. fwiw, there's also the python standard libraries `urlparse` (py2) and `urllib.parse` (py3) that can help with parsing filenames in case the `.split("/")[2]` trick doesn't work for you.

I'm going to close this issue out as I'd like to keep textract as true to the unix philosophy of "do one thing well" as possible. If you'd like to add something to the documentation to demonstrate how to loop over URLs though, that'd be great!
