### ISSUE TITLE
Make textract compatible with Python 3

### ISSUE THREAD

**Issue by bruot** [deanmalmgren/textract#179]
Is there any plan to have textract working with Python 3?

With some quick tests, I saw that PDF extract seems to work but not docx, so maybe there is just some work to do on a few parsers.

**Comment by bruot** [comment]
OK, there is actually ongoing work in PR #126 (that includes #104 and #116)!

**Comment by monkeypants** [comment]
PR #126 is merged, can this tocket be closed?

**Comment by bruot** [comment]
I have tested pdf and docx files with Python 2 and 3 on the master branch. The docx conversion with Python 3 still has an issue. See the attached files.
[traceback.txt](https://github.com/deanmalmgren/textract/files/1671881/traceback.txt)
[test.docx](https://github.com/deanmalmgren/textract/files/1671883/test.docx)

**Comment by jpweytjens** [comment]
Closed by #292
