### ISSUE TITLE
 UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1671: character maps to <undefined>

### ISSUE THREAD

**Issue by somedude2024** [deanmalmgren/textract#190]
I am trying to install this using pip3.6 I am getting an error. 

Doing this install using PYthon 3.6 and on windows. 

`$ pip3.6-script.py install textract
Collecting textract
  Using cached textract-1.6.1.tar.gz
Collecting argcomplete==1.8.2 (from textract)
  Using cached argcomplete-1.8.2-py2.py3-none-any.whl
Collecting chardet==2.3.0 (from textract)
  Using cached chardet-2.3.0-py2.py3-none-any.whl
Collecting python-pptx==0.6.5 (from textract)
  Using cached python-pptx-0.6.5.tar.gz
Collecting docx2txt==0.6 (from textract)
  Using cached docx2txt-0.6.tar.gz
Collecting beautifulsoup4==4.5.3 (from textract)
  Using cached beautifulsoup4-4.5.3-py3-none-any.whl
Collecting xlrd==1.0.0 (from textract)
  Using cached xlrd-1.0.0-py3-none-any.whl
Collecting EbookLib==0.15 (from textract)
  Using cached EbookLib-0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\canmhn\AppData\Local\Temp\pip-build-1vpbi3us\EbookLib\setup.py", line 13, in <module>
        long_description = open('README.md').read(),
      File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1671: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\canmhn\AppData\Local\Temp\pip-build-1vpbi3us\EbookLib\
`

**Comment by francesco1119** [comment]
Yep! Same issue:

![yep](https://user-images.githubusercontent.com/3397477/33803482-8b4d6932-ddf6-11e7-83db-afc555d6375b.PNG)

**Comment by apwork** [comment]
Same issue here, Windows 7 running Python 3.6.2

**Comment by germanmarky** [comment]
Open PR for the EBookLib project [PR#132](https://github.com/aerkalov/ebooklib/issues/132)

**Comment by bzm3r** [comment]
It seems that this has been fixed in https://github.com/aerkalov/ebooklib/pull/138, but the repo author has not been merging changes for a while. Possibly, the package as it stands is dead, is willing to fork and maintain it.

**Comment by pmahend1** [comment]
pip install git+git://github.com/deanmalmgren/textract.git@master

**Comment by shnabz** [comment]
> error: command 'swig.exe' failed: No such file or directory

**Comment by mysteryml** [comment]
`   swig.exe -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    error: command 'swig.exe' failed: No such file or directory`

**Comment by avaish1** [comment]
with http://www.swig.org/download.html, installed successfully on windows 10.

**Comment by Halkaramov2019** [comment]
> > error: command 'swig.exe' failed: No such file or directory

same issue :/

**Comment by aaaaditya23** [comment]
Final solution worked for me 
https://github.com/deanmalmgren/textract

go to above link it has ebooklib==0.16 which sucessfully installs textract

**Comment by jpweytjens** [comment]
I'm closing this issue due to the release of textract version 1.6.3. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.
