### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by jialutu** [deanmalmgren/textract#193]
On my ubuntu xenial server, I had to install the package libpulse-dev (as well as the other packages) for me to be able to install textract. Not sure if it's a problem just for me, so not sure whether this is worth adding to the installation instructions.

**Comment by francesco1119** [comment]
`libpulse-dev` is installed on my Ubuntu Xenial but how did you installed `textract`?

**Comment by jialutu** [comment]
Was your installation Xenial desktop or Xenial server? I've found that I had to specifically install libpulse-dev on Xenial 16.04 server for it to work. This is done by following the install instructions specified in the documentation.

**Comment by francesco1119** [comment]
I had a problem with `pip `on my Xenial Desktop

**Comment by jpweytjens** [comment]
I'm closing this issue due to the release of textract version 1.6.3 which fixes these issues. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.
