### ISSUE TITLE
"ImportError: cannot import name PDFDocument"

### ISSUE THREAD

**Issue by sfsdfd** [deanmalmgren/textract#197]
I installed textract via pip, and then ran this simple Hello, World code:

```
#!/usr/bin/env python2.7
import sys, textract
print(textract.process(sys.argv[1], 'rb'))
```
Here's the dependency error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pdf2txt.py", line 3, in <module>
    from pdfminer.pdfparser import PDFDocument, PDFParser
ImportError: cannot import name PDFDocument
```

This library is DOA until this dependency issue is fixed.

**Comment by jpweytjens** [comment]
I'm closing this issue due to the release of textract version 1.6.3 which fixes these issues. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.
