### ISSUE TITLE
Missing ExtractMsg and other link dependencies

### ISSUE THREAD

**Issue by edgarshvaykovsky** [deanmalmgren/textract#201]
Hello,

After making _pip install textract_ these two dependencies are missing:
https://github.com/goulu/pdfminer/zipball/e6ad15af79a26c31f4e384d8427b375c93b03533#egg=pdfminer.six
https://github.com/mattgwwalker/msg-extractor/zipball/master

That's why msg_parser.py fails with exception:
`No module named ExtractMsg`

Should it be fixed?

Thank you.

**Comment by jpweytjens** [comment]
I'm closing this issue due to the release of textract version 1.6.3 which fixes these issues. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.
