### ISSUE TITLE
Failed building wheel for pocketsphinx

### ISSUE THREAD

**Issue by kld123509945** [deanmalmgren/textract#209]
I install the anaconda3，and use pip install textract in the cmd window.
However, the install is incomplete. This causes other codes to have problems with its invocation.
The warning is as follows:

Building wheels for collected packages: pocketsphinx
  Running setup.py bdist_wheel for pocketsphinx ... error
  Complete output from command C:\Users\w\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\w\\AppData\\Local\\Temp\\pip-build-l78y971l\\pocketsphinx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\w\AppData\Local\Temp\tmplpi7yv4zpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build_ext
  building 'sphinxbase._ad' extension
  swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
  swig.exe -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
  error: command 'swig.exe' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for pocketsphinx
  Running setup.py clean for pocketsphinx
Failed to build pocketsphinx
Installing collected packages: python-pptx, beautifulsoup4, six, EbookLib, chardet, docx2txt, xlrd, argcomplete, pocketsphinx, SpeechRecognition, textract
  Found existing installation: beautifulsoup4 4.6.0
    Uninstalling beautifulsoup4-4.6.0:
      Successfully uninstalled beautifulsoup4-4.6.0
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: chardet 3.0.4
    Uninstalling chardet-3.0.4:
      Successfully uninstalled chardet-3.0.4
  Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
  Running setup.py install for pocketsphinx ... error
    Complete output from command C:\Users\w\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\w\\AppData\\Local\\Temp\\pip-build-l78y971l\\pocketsphinx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\w\AppData\Local\Temp\pip-rdnf9rb9-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'sphinxbase._ad' extension
    swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
    swig.exe -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    error: command 'swig.exe' failed: No such file or directory

    ----------------------------------------
Command "C:\Users\w\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\w\\AppData\\Local\\Temp\\pip-build-l78y971l\\pocketsphinx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\w\AppData\Local\Temp\pip-rdnf9rb9-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\w\AppData\Local\Temp\pip-build-l78y971l\pocketsphinx\

**Comment by kld123509945** [comment]
Now in the Jupyter notebook, the 'import textract' will induce the warning as:
ModuleNotFoundError: No module named 'textract'

**Comment by rajagopalx** [comment]
👍

**Comment by Nikhil-Wagh** [comment]
You might also need to install **libasound**

Try this in addition to above answer.
`sudo apt-get install libasound2-dev`

**Comment by qinyu-us** [comment]
I ran into same issue. But have python 3.6, swig installed on windows 10 but still can't have pocketsphinx installed.

**Comment by ucals** [comment]
> You might also need to install **libasound**
> 
> Try this in addition to above answer.
> `sudo apt-get install libasound2-dev`

This worked for me! Thanks!

**Comment by PallawiSinghal** [comment]
> You might also need to install **libasound**
> 
> Try this in addition to above answer.
> `sudo apt-get install libasound2-dev`

Thank u

**Comment by pavan1996** [comment]
> I too faced the similar problem.
> 
> Try this:
> 
> `sudo apt-get install -y python python-dev python-pip build-essential swig git libpulse-dev`
> 
> `pip install pocketsphinx`
> 
> Reference:
> 
> https://github.com/cmusphinx/pocketsphinx-python

**Comment by scote89** [comment]
Im getting the same issue but not using Ubuntu. Nothing is working. Any idea we can still fix it without Ubuntu?
- I have swig installed correctly
- I have VisualStudio 2019 installed 
- I added pocketsphinx in binary. Now when I try pip installing pocketsphinx, it says: already satisfied (0.1.15)

**Comment by idansc** [comment]
running on mac, same problem with python3

**Comment by shansen5** [comment]
Thank you.  I had the same error, on Ubuntu 19.04, python 3.6.7.  These two commands allowed me to successfully install picketspinx (for textract).
```
sudo apt-get install -y python python-dev python-pip build-essential swig git libpulse-dev
sudo apt-get install libasound2-dev
```

**Comment by akshay-salvi** [comment]
can anyone have the solution for windows

**Comment by scote89** [comment]
I unfortunately ended up having to switch to using Pymupdf instead which is
similar and also very powerfull.

**Comment by abdowiss** [comment]
on windows I have solve this problem with :
git clone --recursive https://github.com/cmusphinx/pocketsphinx-python/
cd pocketsphinx-python
python setup.py install

mor info https://github.com/cmusphinx/pocketsphinx-python

**Comment by jpweytjens** [comment]
I'm closing this issue due to the release of textract version 1.6.3. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.

**Comment by its-luka-k** [comment]
I am having the same issue on Mac (Python3)... Any advice?

**Comment by ikostan** [comment]
Hi all.

I came a cross with this issue while trying to setup Docker + python 3.7 image for automation purposes. Following code solve the problem:

`apt-get install -y python-dev python-pip build-essential swig git libpulse-dev libasound2-dev`

Thanks

**Comment by MahmoudSaeedNST** [comment]
i work on windows 10 with Anaconda Environment and i install swig , but this command `pip install pocketsphinx` also return 
Running setup.py install for pocketsphinx ... error
    ERROR: Command errored out with exit status 1:
    ...
Complete output (6 lines):
    running install
    running build_ext
    building 'sphinxbase._sphinxbase' extension
    swigging deps/sphinxbase/swig/sphinxbase.i to deps/sphinxbase/swig/sphinxbase_wrap.c
    C:\ProgramData\Anaconda3\Library\bin\swig.exe -python -modern -threads -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o deps/sphinxbase/swig/sphinxbase_wrap.c deps/sphinxbase/swig/sphinxbase.i
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by tlscabinet** [comment]
> I am having the same issue on Mac (Python3)... Any advice?

did u solved the problem?

**Comment by MahmoudSaeedNST** [comment]
> 
> 
> > I am having the same issue on Mac (Python3)... Any advice?
> 
> did u solve the problem?

actually i didn't solve it on windows Environment, i had change my OS to Ubuntu to solve problems

**Comment by jalakamkiranadspl** [comment]
> Thank you. I had the same error, on Ubuntu 19.04, python 3.6.7. These two commands allowed me to successfully install picketspinx (for textract).
> 
> ```
> sudo apt-get install -y python python-dev python-pip build-essential swig git libpulse-dev
> sudo apt-get install libasound2-dev
> ```

This worked for me. I am using Ubuntu20.04 by the way.

**Comment by koraykoca** [comment]
sudo apt-get install -y python python-dev python3-pip build-essential swig git libpulse-dev
sudo apt-get install libasound2-dev

**Comment by GEJ1** [comment]
> sudo apt-get install -y python python-dev python3-pip build-essential swig git libpulse-dev sudo apt-get install libasound2-dev

Thank you! This works for me on Ubuntu 20.04
