### ISSUE TITLE
pyttsx3 in Ubuntu is not outputting an audio!

### ISSUE THREAD

**Issue by Aravinviju** [deanmalmgren/textract#230]
Hi, I am trying to implement 'speech to text to speech' using python's pyttsx3 and speech_recognition!

Though it is not showing any error, it is also not outputting any audio too.

Below is the code i used to test it:

import speech_recognition
import pyttsx3
speech_engine = pyttsx3.init() 
speech_engine.setProperty('rate', 150)
speech_engine.say('Sally sells seashells by the seashore.')

Any help is appreciated!

**Comment by jpweytjens** [comment]
I'm closing this issue as does not seem related to `textract`. If you can eloborate how this is related to the latest version of `textract`, feel free to leave a comment with additional information and I'll reopen the issue.
