### ISSUE TITLE
MS PowerPoint 2003 (PPT) not yet supprted

### ISSUE THREAD

**Issue by tomrwillis** [deanmalmgren/textract#235]
I'm writing a python script to scan for certain text in all flavor of MS Office docs and cannot find anything to read the text out of older MS Office PPT files

**Comment by mikkhait** [comment]
https://github.com/deanmalmgren/textract/issues/153

**Comment by jpweytjens** [comment]
Are you aware of any tool that can parse powerpoint files?

**Comment by jpweytjens** [comment]
`ppt` files will supported in the upcoming version with Libre Office as parser.
