### ISSUE TITLE
.tex Latex support

### ISSUE THREAD

**Issue by impredicative** [deanmalmgren/textract#264]
Is it possible to get support for .tex Latex files?

**Comment by jpweytjens** [comment]
@impredicative What do you specifically have in mind with `.tex` support? In general, parsing `.tex` files and removing all LaTeX code is a non trivial task. There are tools such as [DeTex](https://github.com/pkubowicz/opendetex) and [pandoc](https://pandoc.org/) that allow converting `.tex` to `.txt` files which can be parsed with textract.

If this is sufficient, I encourage you to open a PR that adds support for either of these tools. If you have anything else in mind, please elaborate.

**Comment by jpweytjens** [comment]
Support for `.tex` files will be added in the upcoming version with pandoc and opendetex as parsers.
