### ISSUE TITLE
Textract is outdated in terms of requirements

### ISSUE THREAD

**Issue by tvrbanec** [deanmalmgren/textract#267]
textract 1.6.1 has requirement chardet==2.3.0, but you'll have chardet 3.0.4 which is incompatible.
textract 1.6.1 has requirement six==1.10.0, but you'll have six 1.12.0 which is incompatible.

**Comment by PifPof73** [comment]
Hi,
@maintainers:
Could you please type a >= in the requirements to keep the package more usable for the future?

@tvrbanec:
You still can use it inside virtual environment, there you can install it with the old versions of the 3rd party libraries. See [https://docs.python.org/3/library/venv.html](url).

Regards,
PifPof73

**Comment by tvrbanec** [comment]
@PifPof73
Good ideas!
I am using virtual environment on second computer. I want to finish programming my software. When I started few years ago, I started with Python 3, but there was several modules that was not available on it, so I had to switch on 2.7, where I'am stuck for now until I finish my job.

**Comment by StevenMapes** [comment]
Does this help https://github.com/deanmalmgren/textract/issues/220#issuecomment-444155771

**Comment by jerr0328** [comment]
This is also conflicting with other packages. For instance, jsonschema 3.0 pre-releases require six>=1.11.0 (source: https://github.com/Julian/jsonschema/blob/v3.0.0b3/setup.cfg#L31).

In general, the requirements in setup.py should not be pinned unless there's a specific reason. For instance, if there's something used in version 1.10 of six, the version specifier should be something like `>=1.10` or `>=1.10,<2` if you want to be safe from breaking changes.

**Comment by sherpadee** [comment]
I got it running on OSX High Sierra  Python 3.7.2 with this:
`brew reinstall swig python`
`pip install pocketsphinx`
`pip install git+https://github.com/sherpadee/textract`

**Comment by DanAtShenTech** [comment]
I just discovered that @deanmalmgren [asked for someone else to take over this repo](https://github.com/deanmalmgren/textract/issues/117) back in 2016.

**Comment by jekozyra** [comment]
@DanielSwain / @jpweytjens - as the new maintainers, is there any timeline for getting the dependency issues resolved? This would be a great starting place for getting this to more usable state.

**Comment by jpweytjens** [comment]
> 
> 
> @DanielSwain / @jpweytjens - as the new maintainers, is there any timeline for getting the dependency issues resolved? This would be a great starting place for getting this to more usable state.

I plan to have the dependency and installation issued solved by the end this week (i.e., before or at 09/06). I don't expect this to take too much time, but I'd rather leave some wiggle room for unexpected events.

**Comment by jpweytjens** [comment]
Closed by #292
