### ISSUE TITLE
Correlation or Association rule of phrases and answers to them

### ISSUE THREAD

**Issue by jasperDD** [deanmalmgren/textract#271]
Maybe i am  asking in the wrong  topic, but maybe someone will hint where to look for research by this task(github or kaggle).
 I try find methods, methodology to create predicative model. Namely, I want to investigate the relationship between the sentences and the answer to them. For example when person communicate they often say

person1:Hi, how are you?
person2:Fine, thank you.

In some sense, this is a correlation between the text and or the rules of associations and answer phrases, if the phrase is  x then answer is y

I have big dataset with dialogs between people (~100Gb txt files with different dialogs of daily speech) What method in line of Text Mining can I use to learn that if one person said such a phrase, then on this phrase is usually answered with such a phrase (or a set of words)?
any help appreciated

**Comment by jpweytjens** [comment]
Closed as off topic. You might want to look at [NLTK](https://www.nltk.org/) and/or [scikit-learn](https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html).
