### ISSUE TITLE
Pocketsphinx as optional for Windows

### ISSUE THREAD

**Issue by ahartikainen** [deanmalmgren/textract#274]
Hi, could the `pocketsphinx` be optional dependency on Windows. It seems that currently building pocketsphinx is not trivial task on Windows.

How many functions need pocketsphinx and if there are not too many, maybe they could raise an error if the user tries to use that functionality without pocketsphinx installed.

**Comment by LeedsLad** [comment]
Hi, even on Mac I'm getting errors. I can install Pocketsphinx independently but then textract doesn't recognise that it's installed. Textract tries to install it itself but it fails... I don't need audio processing!

**Comment by zxv** [comment]
It would be great if we could make speech recognition dependencies optional in general (not just on windows). This would simplify installation of the package in cases where that functionality is not needed. I ran into some installation issues for pocketsphinx and ended up needing to fork and modify the requirements to get a working installation of textract.

**Comment by jpweytjens** [comment]
Closed by #292
