### ISSUE TITLE
Can't install textract with requests.

### ISSUE THREAD

**Issue by misingnoglic** [deanmalmgren/textract#280]
When I try to do this, I get this error, since the chardet dependency is pinned at 2.3.0

Exception message: Could not satisfy all requirements for chardet==2.3.0:
    chardet==2.3.0(from: textract==1.6.1), chardet<3.1.0,>=3.0.2(from: requests==2.18.4)

**Comment by misingnoglic** [comment]
For now my solution is to downgrade to 1.5.0, but that isn't great.

**Comment by yodermk** [comment]
^^^ thanks for that.  Now, please please please push a rease to pypy. :)

**Comment by jpweytjens** [comment]
Closed by #292
