### ISSUE TITLE
Is textract still being maintained?

### ISSUE THREAD

**Issue by bruot** [deanmalmgren/textract#289]
Hi. I see that most issues are not commented by contributors and there are also many pull requests that would only require minimal work to test and accept. As a result the last commit in the master branch is nearly two years old.
Is someone still maintaining textract?
Given the popularity of this project, I think it should not die.

**Comment by deanmalmgren** [comment]
Thanks for the note @bruot . As I [shared here](https://github.com/deanmalmgren/textract/issues/117#issuecomment-496749238), @jpweytjens and @DanielSwain are co-maintaining this project now, but this is good feedback for our approach to date. 

I, too, would rather not have this project die but I am not in a position to manage the day-to-day responsibilities of it anymore.

**Comment by jpweytjens** [comment]
Please see #194 for some more information about the upcoming pull request to fix the installation issues.

**Comment by bruot** [comment]
@deanmalmgren Thanks for the feedback. @jpweytjens I hope you will find some time soon to fix at least the big issues the project is having!

**Comment by deanmalmgren** [comment]
Please don't hesitate to help us fix the issues, too! The success of
maintaining open source software critically relies on the community's
engagement.
