### ISSUE TITLE
Cannot install textract from pypi

### ISSUE THREAD

**Issue by sharath-psh** [deanmalmgren/textract#291]
i have the latest python installed and all the requirements satisified.

when i try to install from the the pypi. pip install textract.

i get the following error : 

'''

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Sharath\AppData\Local\Temp\pip-install-7xld3a_6\EbookLib\setup.py", line 13, in <module>
        long_description = open('README.md').read(),
      File "c:\program files (x86)\python37-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1671: character maps to <undefined>
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Sharath\AppData\Local\Temp\pip-install-7xld3a_6\EbookLib\

'''

**Comment by jotauses** [comment]
I just have to use this library and I had the same problem but I fixed it. When you pass that error you will get another one.

You are using Windows, right?

1. Download Swig for Windows [Swig](https://netix.dl.sourceforge.net/project/swig/swigwin/swigwin-3.0.12/swigwin-3.0.12.zip) and create a system variable pointing to the swig.exe directory.

2. Dowload this library [(textract)](https://github.com/deanmalmgren/textract.git) and change the requirements of EbookLib==0.16 to EbookLib==0.17.1 (textract-master\requirements\python).

3. Install now the library executing python setup.py install.

**Comment by sharath-psh** [comment]
Thank you.

Followed your steps and now it is working perfectly fine.
