### ISSUE TITLE
ShellError: The command `pdftotext علی.pdf -` failed with exit code 1

### ISSUE THREAD

**Issue by Keramatfar** [deanmalmgren/textract#311]
**Describe the bug**
I am trying to open a pdf file that is in a path with Persian characters, and get the above error.
**To Reproduce**

> a = 'علی.pdf'
> text = textract.process(a)

**Expected behavior**
To process the file as usual.

**Comment by jpweytjens** [comment]
I can't reproduce this error on my system(s). Can you provide additional information? In particular

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Textract version [e.g. 1.6.3]
 - Python version [e.g. 3.7]
 - Virtual environment (yes/no)

**Comment by Keramatfar** [comment]
Thanks, I solved it by updating my Anaconda to last version.
