### ISSUE TITLE
Unable to extract table from pdf in right format

### ISSUE THREAD

**Issue by BVSREDDY82** [deanmalmgren/textract#318]
Unable to extract table data using pdf, The data should be displayed as rows and columns however data is displaying in columns only

id  |   name        | designation
1   |   Ram         | engineer
2   |   Sandeep  | engineer

**Expected behavior**
id       name         designation
1        Ram          engineer
2        Sandeep   engineer

**Actual Behavior**
id
1
2
name
Ram
Sandeep
designation
engineer
engineer

**Comment by BVSREDDY82** [comment]
Please provide alternate solution or flexibility to convert into html format from pdf format as pdfminer is allowing it. Best to have this feature via textract instead of custom coding.

**Comment by jpweytjens** [comment]
What kind of options do you need to pass to pdfminer to allow the desired format?

**Comment by BVSREDDY82** [comment]
Can close the issue as PDF miner has no proper simple provision of displaying multi column tabular data

**Comment by cmeb45** [comment]
[Tabula](https://github.com/tabulapdf/tabula), or more specifically, [its Python wrapper](https://github.com/chezou/tabula-py) provides great functionality for extracting tables from PDFs.

Perhaps it could be added as an option alongside Tesseract and pdfminer in textract's PDF parser?

**Comment by cmeb45** [comment]
[Tabula](https://github.com/tabulapdf/tabula), or more specifically, [its Python wrapper](https://github.com/chezou/tabula-py) provides great functionality for extracting tables from PDFs.

Perhaps it could be added as an option alongside Tesseract and pdfminer in textract's PDF parser?
