### ISSUE TITLE
Extract text from image "ticket"

### ISSUE THREAD

**Issue by hanane2019** [deanmalmgren/textract#319]
![example_04](https://user-images.githubusercontent.com/48124896/71534178-26bd5280-28fd-11ea-9e87-133ec69d711f.png)

Hello everybody,

I’ve used many python libraries to extract the text from these tickets but they did not give me correct results.
I even applied a filter and a preprocessing on these images but I could not extract all the text from them, especially the elements that want to extract are the date and the time and the amount TTC and the serial number located in the middle of the ticket like 31950 A 34.
Could anyone please help me with this?

**Comment by jpweytjens** [comment]
Textract is a wrapper for other tools. It doesn't implement any text extraction methods itself. I would recommend following the Tesseract [advice](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) for better extraction and go from there. I'm closing this issue as it's not directly related to textract.
