### ISSUE TITLE
Is textract dead or alive (under active development)?

### ISSUE THREAD

**Issue by MartinThoma** [deanmalmgren/textract#350]
I see that the last commit is more than half a year ago, that the build and the docs are failing. This indicates that textract might not be under active development.

You might want to add the [trove classifier](https://pypi.org/classifiers/) `Development Status :: 7 - Inactive` to the project.

**Comment by jpweytjens** [comment]
I'm working on version 2.0 of Textract, but have failed to keep up with the issues posted in recent times. I hope to have a first beta version of textract 2.0 in the next weeks.

**Comment by infinityplusone** [comment]
@jpweytjens Any update/ETA for this?
