### ISSUE TITLE
PDF decoder encoding issue. Found temporary fix.

### ISSUE THREAD

**Issue by Vbansal21** [deanmalmgren/textract#383]
By default the `pdf_parser.process` automatically detect encoding for the decoding (textract/parsers/utils.py => line 64), but it doesn't always work properly, so there should be an option to specify decoder's encoding.
Current temporary solution(line 34 onwards):
`

    def process(self, filename, encoding, **kwargs):
        """Process ``filename`` and encode byte-string with ``encoding``. This
        method is called by :func:`textract.parsers.process` and wraps
        the :meth:`.BaseParser.extract` method in `a delicious unicode
        sandwich <http://nedbatchelder.com/text/unipain.html>`_.

        """
        # make a "unicode sandwich" to handle dealing with unknown
        # input byte strings and converting them to a predictable
        # output encoding
        # http://nedbatchelder.com/text/unipain/unipain.html#35
        byte_string = self.extract(filename, **kwargs)
        unicode_string = self.decode(byte_string,encoding)  #CHANGED HERE
        return self.encode(unicode_string, encoding)

    def decode(self, text, encoding=None):    #CHANGED HERE
        """Decode ``text`` using the `chardet
        <https://github.com/chardet/chardet>`_ package.
        """
        # only decode byte strings into unicode if it hasn't already
        # been done by a subclass
        if isinstance(text, six.text_type):
            return text

        # empty text? nothing to decode
        if not text:
            return u''

        # use chardet to automatically detect the encoding text
        result = chardet.detect(text)
        encoding = result['encoding'] if encoding == None else encoding   #CHANGED HERE
        return text.decode(encoding)
`

**Comment by deanmalmgren** [comment]
Would you like to make a pull request for this?

**Comment by Vbansal21** [comment]
Thanks for your response 😊.

I'm currently reinstalling my os(Ubuntu), corrupted the previous install. Won't be able to make a PR for some time😅. Will do so when my setup is complete.
