### ISSUE TITLE
Travis CI is broken

### ISSUE THREAD

**Issue by traverseda** [deanmalmgren/textract#387]
It looks like Travis CI is currently broken, and I can't add this repo, I think only @deanmalmgren can. @deanmalmgren can you go to https://travis-ci.com/ and add this repository? travis-ci.org is apparently now defunct.

**Comment by deanmalmgren** [comment]
I just got textract set up on travis-ci.com. All I can say is WOW did
Travis CI bungle the transition from .org to .com. @traverseda @jpweytjens
you should have access to the Travis CI build now. The build is failing,
but at least Travis CI is working again.
https://travis-ci.com/github/deanmalmgren/textract

Can you take it from here @traverseda?

**Comment by traverseda** [comment]
Yep, I think that covers all the steps I couldn't do myself. Thanks!
