### ISSUE TITLE
Error extracting text from pdf

### ISSUE THREAD

**Issue by sirwentemi** [deanmalmgren/textract#396]
**Describe the bug**
I need help figuring out how to resolve this error, when I run code below
`text = textract.process("C:/Users/house-phase/Desktop/topic-modelling/pdf/JC.pdf", method='pdfminer')`
![image](https://user-images.githubusercontent.com/70702128/132118473-7c6684b0-da62-41f7-b266-fad9ef103bef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Textract version :  1.6.4
 - Python version : Python 3.8.5
 - Virtual environment (no)
 Thanks in advance

**Comment by jpweytjens** [comment]
Windows path contain forward slashes that don't get interpreted correctly when using a string. You can either use a raw string `r"C:/Users/house-phase/Desktop/topic-modelling/pdf/JC.pdf"`  or the `pathlib` library to handle the slashes for you.

```
import pathlib
file = pathlib.Path("C:/Users/house-phase/Desktop/topic-modelling/pdf/JC.pdf")
text = textract.process(str(file), method='pdfminer'
```
