### ISSUE TITLE
remove tesseract version info from extracted text

### ISSUE THREAD

**Issue by deanmalmgren** [deanmalmgren/textract#48]
It looks like every image processed with textract has a message like `Tesseract Open Source OCR Engine v3.02 with Leptonica` at the beginning. This appears to be printed to standard out and is not a reflection of the text that is actually in the document:

``` shell
vagrant@dev:/vagrant$ textract tests/gif/i_heart_gifs.gif
Tesseract Open Source OCR Engine v3.02 with Leptonica
TEXT


vagrant@dev:/vagrant$ tesseract tests/gif/i_heart_gifs.gif kk.txt
Tesseract Open Source OCR Engine v3.02 with Leptonica
vagrant@dev:/vagrant$ cat kk.txt.txt 
TEXT

vagrant@dev:/vagrant$ tesseract tests/jpg/i_heart_jpegs.jpg gg.txt
Tesseract Open Source OCR Engine v3.02 with Leptonica
vagrant@dev:/vagrant$ tesseract tests/jpg/i_heart_jpegs.jpg gg.txt > kk
vagrant@dev:/vagrant$ cat kk
Tesseract Open Source OCR Engine v3.02 with Leptonica
```

This should be a simple fix of just redirecting the output of the tesseract command in a smarter way, but I'm in the middle of something else and thought I'd create a placeholder issue in case someone else has the time to address it.

**Comment by davidsonsns** [comment]
only the code below got success:

tesseract infile.png outprefix 1>/dev/null 2>&1

**Comment by deanmalmgren** [comment]
@davidsonsns is this still an issue?

**Comment by monika297** [comment]
@deanmalmgren, I am using tesseract --version
tesseract 3.03
 leptonica-1.70
  libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0

At the time of image processing, I am getting a couple of error messages which is filling up my error logs. They are: 
Tesseract Open Source OCR Engine v3.03 with Leptonica
Error in pixCreateNoInit: pix_malloc fail for data
Error in pixCreate: pixd not made
Error in pixBlockconvAccum: pixd not made
Error in pixBlockconvGray: pixt not made
Error in pixGetWidth: pix not defined
Error in pixGetHeight: pix not defined

Could you please suggest what is wrong?
Looking forward to your help.

Thanks,
Monika

**Comment by deanmalmgren** [comment]
@monika297 I'm sorry to hear you're having trouble with tesseract. In this case, I might suggest putting this issue on StackOverflow to see if others can help. It sounds like an issue with tesseract :( 

There may either be a problem with the image or maybe a memory allocation issue (what else is running on your server?), but I'm not enough of a tesseract expert to know for sure

Best of luck,
Dean
