### ISSUE TITLE
xlsx multiple worksheet

### ISSUE THREAD

**Issue by tomron** [deanmalmgren/textract#68]
xlsx reader failed to read data from multiple sheets. It read data from only one sheet rather than either failing or reading all.

**Comment by deanmalmgren** [comment]
I also tested and confirmed that this is not an issue with the current version of textract on [this multipage excel spreadsheet](https://docs.google.com/a/datascopeanalytics.com/spreadsheets/d/1dETV3IwSWHrF4phrVJJzJhxX4W_C9oPiRwE3IbPJ6dA/edit#gid=1201089073):

```sh
vagrant@dev:/vagrant$ textract multipage.xlsx

a b c d
1.0 2.0 3.0 4.0
```
I'm not sure if this happened to get fixed somewhere along the way or if we have a dependency version problem, but if you continue to have this issue @tomron, please feel free to reopen this issue and I'll be happy to look into it for you. In the meantime, I'm going to close this out.
