### ISSUE TITLE
support for .tiff

### ISSUE THREAD

**Issue by ebin123456** [deanmalmgren/textract#81]
please add support for  .tiff

**Comment by deanmalmgren** [comment]
Sounds like a great idea and should be pretty straightforward. I'm 95% sure that tesseract OCR supports .tiff's and, if not, we can always convert a .tiff to a .png and then do OCR on the resulting .png file.

I'll get to this when I can, but if you're interested in the meantime, it should be pretty straightforward to use the [jpg parser](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/jpg_parser.py) as a template.
